linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace
    - wsl
